WebApplication1/Models/Pan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Biz;

namespace WebApplication1.Models
{
    public class Pan
    {
        public long Id { get; set; }


        [LiteDB.BsonIgnore]
        public string UserIdX
        {
            get
            {
                if (this.UserId <= 0) return "";
                var userLst = DbHelper.GetFirst<User>(P => P.Id == this.UserId);

                return userLst?.Name??"";
            }
        }

        public long UserId { get; set; }

        public long ParentId { get; set; }


        public long[] Roles1 { get; set; }
        public long[] Roles2 { get; set; }
        public long[] Roles3 { get; set; }
        [LiteDB.BsonIgnore]
        public string Roles11
        { get
         {
            if (this.Roles1 == null) return "";
               var userLst = DbHelper.GetAll<User>().OrderByDescending(p => p.SeqNo).ToList();
                var names = new List<string>();
                foreach (var r in this.Roles1)
                {
                    var n = userLst.FirstOrDefault(p => p.Id == r);
                    if (n!=null) { names.Add(n.Name); }
                }
                return string.Join(",", names);
            }
        }
        [LiteDB.BsonIgnore]
        public string Roles22
        {
            get
            {
                if (this.Roles2 == null) return "";
                var userLst = DbHelper.GetAll<User>().OrderByDescending(p => p.SeqNo).ToList();
                var names = new List<string>();
                foreach (var r in this.Roles2)
                {
                    var n = userLst.FirstOrDefault(p => p.Id == r);
                    if (n != null) { names.Add(n.Name); }
                }
                return string.Join(",", names);
            }
        }
        [LiteDB.BsonIgnore]
        public string Roles33
        {
            get
            {
                if (this.Roles3 == null) return "";
                var userLst = DbHelper.GetAll<User>().OrderByDescending(p => p.SeqNo).ToList();
                var names = new List<string>();
                foreach (var r in this.Roles3)
                {
                    var n = userLst.FirstOrDefault(p => p.Id == r);
                    if (n != null) { names.Add(n.Name); }
                }
                return string.Join(",", names);
            }
        }
        [LiteDB.BsonField("name")]
        public string Name { get; set; }

        public string Url { get; set; }
        [LiteDB.BsonField("seqno")]
        public int SeqNo { get; set; }
      
        [LiteDB.BsonField("status")]
        public int Status { get; set; }

       
        public string Ext { get; set; }

        public long Size { get; set; }
        public DateTime LastTime { get; set; }
    }
}

WebApplication1/Controllers/PanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Biz;
using Newtonsoft.Json;

namespace WebApplication1.Controllers
{
    public class PanController : ControllerBase
    {
        [Route("/ajax/pan")]
        [HttpGet]
        public IActionResult Ajax(long parentId)
        {
           // DbHelper.Remove<Pan>(P=>P.Id>0);
            parentId = parentId == 0 ? 1 : parentId;
            var lst = DbHelper.GetAll<Pan>();
             lst = lst.Where(p=>p.ParentId==parentId).OrderByDescending(p => p.SeqNo).ToList();


            lst = lst.Where(p => p.Status == 1).ToList();

            var lstall = new List<Pan>();

            var lst1 = lst.Where(p => string.IsNullOrEmpty(p.Ext)).OrderByDescending(p => p.SeqNo).ThenByDescending(p=>p.LastTime);
            var lst2 = lst.Where(p => !string.IsNullOrEmpty(p.Ext)).OrderByDescending(p => p.SeqNo).ThenByDescending(p => p.LastTime);

            lstall.AddRange(lst1);
            lstall.AddRange(lst2);
            var ret2 = new
            {
                code = 0,
                msg = "",
                count = 30,
                data = lstall
            };

            return Json(ret2, new JsonSerializerSettings { Converters = new List<JsonConverter> { new CustomJsonConverter { PropertyNameCase = ConverterPropertyNameCase.Ming } } });
        }
        [Route("/ajax/pan/add")]
        [HttpGet]
        public IActionResult bumenadd(string name, long parentId)
        {
            DbHelper.Add(new Pan() { Id = Util.GetCurrentTimeUnix(), Name = name,
                SeqNo = 1, Status = 1, ParentId= parentId,
                LastTime=DateTime.Now,
                 Ext="",
                  Size=0,
                   Roles1=new long[] { },
                Roles2 = new long[] { },
                Roles3 = new long[] { },
                UserId = UserHelper.getcurrUserId(Request)
                     
            });

            var ret2 = new { code = 0, msg = "新增成功" };

            return Json(ret2);
        }
        [Route("/ajax/pan/updateroles")]
        [HttpGet]
        public IActionResult bumenadd(long panid, string userids, string type)
        {
            userids = userids ?? "";
            var pan= DbHelper.GetFirst<Pan>(p => p.Id == panid);

            var user = userids.Split(",",StringSplitOptions.RemoveEmptyEntries);
            var users = new List<long>();
            foreach (var u in user)
            {
                if (long.TryParse(u, out long _u)) {
                    users.Add(_u);
                }
            }
            if(type=="1")
            pan.Roles1 = users.ToArray();
            if (type == "2")
                pan.Roles2 = users.ToArray();
            if (type == "3")
                pan.Roles3 = users.ToArray();
            DbHelper.Update(pan);
            var ret2 = new { code = 0, msg = "更改成功" };

            return Json(ret2);
        }

        [Route("/ajax/pan/path")]
        [HttpGet]
        public IActionResult path(long parentid)
        {
            var pans = DbHelper.GetAll<Pan>();

            var nav = new List<string>();

            var parentid2 = parentid;
            while (true)
            {
                var pan = pans.FirstOrDefault(p => p.Id == parentid2);

                if (pan == null ||  pan.ParentId == 0)
                {
                    break;
                }
                parentid2 = pan.ParentId;
                var name = pan.Name;
                if (name.Length>6)
                { name = name.Substring(0, 5) + ".."; }
                nav.Add($@"<li class='path'>
                    <a href='javascript:void(0);' onclick='onchage2(this, ""pan?parentId={pan.Id}"");'><i class='layui-icon'>&#xe602;</i> {name}</a>
                    </li>");
            }

            var arr = nav.ToArray();
            Array.Reverse(arr);
            var ret2 = new { code = 0, msg =string.Join("", arr) };

            return Json(ret2);
        }


        [Route("/ajax/pan/roles")]
        [HttpGet]
        public IActionResult panrole(long parentid)
        {

            var ret= HasRole(parentid);
            var ret2 = new { code = 0, msg = "", data= ret };

            return Json(ret2);
        }
    }
}

WebApplication1/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }
        public async Task<IActionResult> OnPostMingAsync(IFormFile file)
        {
            var mm = "";
            return null;
        }
        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

WebApplication1/Pages/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.Controllers;
using WebApplication1.Models;

namespace WebApplication1.Pages
{
    public class PageModelBase : PageModel
    {
        public User user { get; set; }
        public bool isAdmin { get; set; }
        public void checklogin()
        {
            user = UserHelper.getcurrUser(Request);
            if (user == null)
            {
                Response.Redirect("login.html", false);
                
            }
            isAdmin = UserHelper.isAdmin(Request);
        }


    }

    public class HomeModel : PageModelBase
    {
        public void OnGet()
        {
            checklogin();

        }
    }
}

WebApplication1/Pages/pan.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.Controllers;

namespace WebApplication1.Pages
{
    public class panModel : PageModel
    {
        public string parentId { get; set; }
        public bool isAdmin { get; set; }
        public bool isCanUpdateFileName { get; set; }
        public void OnGet()
        {
            parentId = Request.Query["parentId"];
            isAdmin = UserHelper.isAdmin(Request);
            parentId = string.IsNullOrEmpty(parentId) ? "1" : parentId;
            long.TryParse(parentId, out long _parentId);
            isCanUpdateFileName = UserHelper.isCanUpdateFileName(_parentId, Request);
        }
    }
}

WebApplication1/Pages/About.cshtml
@page
@using WebApplication1.Pages
@model WebApplication1.Pages.AboutModel
@{
    ViewData["Title"] = "About";
}
<link href="~/js/uploadfile.css" rel="stylesheet">
<script src="~/js/jquery.min.js"></script>
<script src="~/js/jquery.form.js"></script>
<script src="~/js/jquery.uploadfile.js"></script>

<div class="row">
    <div class="col-md-12">
        <div id="fileuploader">Upload</div>
    </div>
</div>
<div id="extrabutton" class="ajax-file-upload-green">开始上传</div>


@*<form method="POST" enctype="multipart/form-data">
    <div>Name: <input name="name" /></div>
    <input type="file" name="file"/>
    <input type="submit" asp-page-handler="Ming"
           asp-page="./tools/UploadFile" value="测试" />
</form>*@
<script>

    $(document).ready(function () {
        var extraObj = $("#fileuploader").uploadFile({
            url: "/tools/Upload",
            statusBarWidth: 'auto',
            dragdropWidth: 'auto',
            showDelete: false,
            showDownload: false,
            showCancel:false,
            autoSubmit: false,
            showProgress: true,
            extraHTML: function () {
             
                var html = "<div><b>名称:</b><input type='text' name='tags' value='' /> <br/>";
                html += "</div>";
                return html;
            },
            afterUploadAll: function(obj) {
                console.log("-------");
                console.log(obj);
                console.log("-------");
            },
            deleteCallback: function (data, pd) {
                $.post("../Home/DeleteFile?url=" + data.url,
                    function (resp, textStatus, jqXHR) {
                        //Show Message
                        console.log(resp, textStatus);
                        alert(resp.msg);
                        pd.statusbar.hide(); //You choice.
                    });
            },
            downloadCallback: function (json, pd) {
                console.log(pd);
                window.open('../Home/DownloadFile?url=' + json.url, "_blank");
            }
        });
        $("#extrabutton").click(function () {
            extraObj.startUpload();
        });
    });
</script>

WebApplication1/Pages/Home.cshtml
@page
@model WebApplication1.Pages.HomeModel
@{
    ViewData["Title"] = "Home";
}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


    <script src="~/js/jquery.min.js"></script>
    <link href="~/css/zh-cn.default.css" rel="stylesheet" />  
    
    <!--[if lt IE 9]>
    <script src='http://cdn.zentaopm.com/9.6.3/js/html5shiv/min.js?v=9.6.3' type='text/javascript'></script>
    <script src='http://cdn.zentaopm.com/9.6.3/js/respond/min.js?v=9.6.3' type='text/javascript'></script>
    <![endif]-->
    <!--[if lt IE 10]>
    <script src='http://cdn.zentaopm.com/9.6.3/js/jquery/placeholder/min.js?v=9.6.3' type='text/javascript'></script>
    <![endif]-->
    <link href="~/layui/css/layui.css" rel="stylesheet" />
    <script src="~/layui/layui.js"></script>

</head>
<body class="m-my-index" style="">
    <header id="header">
        @*<div id="topbar">
            <div class="pull-right" id="topnav">
                <div class="dropdown" id="userMenu">
                    <a href="javascript:;"><i class="layui-icon">&#xe612;</i> 当前用户: @Model.user?.Name  </a><ul class="dropdown-menu"></ul>
                </div><a href="javascript:void(0);" onclick="myout();">退出</a>
         
            </div>
            <h5 id="companyname">
                
            </h5>
        </div>*@
        <nav id="mainmenu">
            <ul class="nav">
                <li class="active" data-id="my"><a href="javascript:void(0);" onclick="onchage(this,'pan?parentId=1');" class="active"><i class="layui-icon">&#xe68e;</i>   <span> 我的网盘</span></a></li>
                @if (Model.isAdmin) {
                @*<li data-id="product"><a href="javascript:void(0);" onclick="onchage(this,'part/bumen');">组织</a></li>*@
                @*<li data-id="product"><a href="javascript:void(0);" onclick="onchage(this,'part/userpage');">员工</a></li>*@
                }@*<li data-id="qa"><a href="javascript:void(0);" id="my" onclick="onchage(this,'part/my');">我的帐号</a></li>*@
            </ul>
            <div class="input-group input-group-sm" id="searchbox">
                <div class="input-group-btn" id="typeSelector">
                    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                        <span id="searchTypeName">关键字</span> @*<span class="caret"></span>*@
                    </button><input type="hidden" name="searchType" id="searchType" value="bug">

                </div><input type="text" name="searchQuery" id="searchQuery" value="" onclick="this.value=&quot;&quot;" onkeydown="if(event.keyCode==13) shortcut()" class="form-control" placeholder="">
                <div id="objectSwitcher" class="input-group-btn"><a href="javascript:shortcut();" class="btn">GO! </a></div>
            </div>
        </nav>
        <nav id="modulemenu">
            <ul class="nav">
                <li data-id="account" id="mingnav">
                    <a href='javascript:void(0);' onclick='onchage2(this, "pan?parentId=1")'><i class="layui-icon">&#xe7a0;</i>  &nbsp;全部&nbsp;</a>
                </li>
              
             
            </ul>
        </nav>
    </header>

    <script>
        layui.use('layer', function () { //独立版的layer无需执行这一句
            var $ = layui.jquery, layer = layui.layer; //独立版的layer无需执行这一句

        });
    </script>
    <script>
       
      
        function setIframeHeight(iframe) {
            if (iframe) {
                var iframeWin = iframe.contentWindow || iframe.contentDocument.parentWindow;
                if (iframeWin.document.body) {
                    iframe.height = iframeWin.document.documentElement.scrollHeight || iframeWin.document.body.scrollHeight;
                }
            }
        };

        window.onload = function () {
            setIframeHeight(document.getElementById('iframeid'));
        };

        function reinitIframe() {
            var iframe = document.getElementById("iframeid");
            try {
                var bHeight = iframe.contentWindow.document.body.scrollHeight;
                var dHeight = iframe.contentWindow.document.documentElement.scrollHeight;
                var height = Math.max(bHeight, dHeight);
                iframe.height = height;
                console.log(height);
            } catch (ex) { }
        }
        window.setInterval("reinitIframe()", 2000);
        function onchage(obj, url) {
            $(".nav > li.active").find("a").removeClass("active");
            $(".nav > li.active").removeClass("active");
            $(obj).addClass("active");
            $(obj).parent().addClass("active");
            document.getElementById("iframeid").src = url; 

        }
        function myout() {
            $.getJSON("/ajax/user/out", { }, function (data) {
                
                layer.msg(data.msg);

                location.href = "login.html";
            });
        }
        function onchage2(obj, url) {
        
            document.getElementById("iframeid").src = url;

        }
        function a(p) { alert(p); }
        function reload2() {

            document.getElementById("iframeid").src = document.getElementById("iframeid").src; 
        }
     
    </script>
    <div id="wrap">
        <div class="outer" style="min-height: 773px;">

            <iframe id="iframeid" src="pan" style="min-height: 773px;" frameborder="0" width="100%" scrolling="no"  onload="setIframeHeight(this)" ></iframe>

        </div>


    </div>
    @*<div id="footer">
        999999
    </div>*@
</body>
</html>

WebApplication1/Pages/pan.cshtml
@page
@model WebApplication1.Pages.panModel
@{
    ViewData["Title"] = "pan";
    Layout = "~/Pages/Part/Layout1.cshtml";
}
@*<style>
    #divFly {
        padding: 2px;
     
        position: absolute;
        z-index: 999; 
        top:50%;
        left:38%;
       

    } 
</style>*@


<div class="layui-btn-group demoTable" style="margin-top: -30px">
@if (Model.isAdmin)
{
    <button class="layui-btn" id="panadd">新增文件夹</button>
}
    <button class="layui-btn" id="wenjianadd">上传文件</button>
</div>
    <div id="divFly">
        
    </div>

<table class="layui-table" id="test5" lay-filter="test5"></table>
<div class="layui-btn-group demoTable2">
    <button id="dde" class="layui-btn" data-type="getCheckData">删除选中行</button>
</div>

<script>
    layui.use('upload', function(){
        var $ = layui.jquery
            ,upload = layui.upload;

        //拖拽上传
        upload.render({
            elem: '#wenjianadd'
            , url: '/tools/Upload/'
            , accept: 'file'
            , data: {parentId : @Model.parentId} //可选项。额外的参数，如：{id: 123, abc: 'xxx'}
            , done: function (res) {
                //如果上传失败
                if (res.code > 0) {
                    return layer.msg('上传失败');
                }

                layer.msg('上传成功');
                reload();
            }
            , error: function () {

            }
        });



    });
</script>
@*{{ (d.ext == "" || d.ext == null) ? '<a class="layui-btn layui-btn-xs" lay-event="edit">编辑权限</a>' : '' }}*@

<script type="text/html" id="barDemo">
    @*<a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="detail"></a>*@
    {{#  if(d.ext == "" || d.ext == null){ }}
    <a class="layui-btn layui-btn-xs" lay-event="edit">编辑权限</a>
    {{#  } }}
  
    @*<a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>*@
</script>
<style>
    .mcss {
        color: tomato;
    }
    .hide{display: none}
    .layui-table-cell {
        height: 40px;
        line-height: 40px;}
</style>
<script>
    var parentId = @Model.parentId;

    function c(obj) {
        var b = $(obj).hasClass("layui-btn-disabled");
       
        if (b) {
            return false;
        }
     
    }
    $(function () {
        $("#wenjianadd").addClass("hide");
        $("#dde").addClass("hide");
        $("#panadd").addClass("hide");
        
       


    });
    $("button#wenjianadd5").click(function () {

        layer.open({
            type: 2,
            area: ['700px', '450px'],
            fixed: false, //不固定
            maxmin: true,
            content: 'part/upload3'
        });

    });
    $("button#panadd").click(function () {
        layer.prompt({ title: '输入文件夹名称', formType: 0 }, function (pass, index) {

            $.getJSON("/ajax/pan/add", { name: pass, parentId: parentId }, function (data) {
                layer.close(index);
                layer.msg(data.msg);

                reload();
            });


        });

    });
    $.getJSON("/ajax/bumen", {}, function (json) {
        var data = json.data;
        for (var i in data) {
            var jsonObj = data[i];

            $("#star").append("<option value='" + jsonObj.id + "'>" + jsonObj.name + "</option>");
        }
    });
    function DivFlying2() {
        //$("#divFly").hide();
        //$("#divFly").html("");
        parent.layer.close(mIndex);
    }

    var mIndex = 0;
    function DivFlying(src) {
  
       
       // $("#divFly").html("<img src=" + src + " width=300  />"); 
        mIndex =  parent.layer.open({
            type: 1, 
            title: false,
            closeBtn: 0, shade: 0, fixed :true,
            area: '300px',
            skin: 'layui-layer-nobg', //没有背景色
            shadeClose: true,
            content: '<img src=' + src + ' width=300  />'
        });
    }
    layui.use('table', function () {
        var table = layui.table;

        table.render({
            elem: '#test5'
            , url: '/ajax/PAN/'
            , where: { parentId: parentId}
            , cellMinWidth: 80 //全局定义常规单元格的最小宽度，layui 2.2.1 新增
            , done: function (res, curr, count) {
                $(".laytable-cell-1-3 > a").addClass("layui-btn-disabled");
                $(".laytable-cell-1-4 > a").addClass("layui-btn-disabled");
                
                ////////
                ////////
                $(".aimg").mouseover(function () {

                    DivFlying("/" + $(this).attr("nl"));
                }); 

                $(".aimg").mouseout(function() {
                    DivFlying2();

                }); 
                
                $.getJSON("/ajax/pan/roles",
                    { parentid: parentId },
                    function(obj) {

                        if (obj.data.item1 == true) {
                            $("#wenjianadd").removeClass("hide");
                            $("#dde").removeClass("hide");
                            $("#panadd").removeClass("hide");
                            $(".laytable-cell-1-3 > a").removeClass("layui-btn-disabled");
                            $(".laytable-cell-1-4 > a").removeClass("layui-btn-disabled");
                        }
                        if (obj.data.item2 == true) {
                            $("#wenjianadd").removeClass("hide");
                        
                            $(".laytable-cell-1-3 > a").removeClass("layui-btn-disabled");
                            $(".laytable-cell-1-4 > a").removeClass("layui-btn-disabled");
                        }
                        if (obj.data.item1 == true) {
                           
                            $(".laytable-cell-1-3 > a").removeClass("layui-btn-disabled");
                           
                        }
                    });
                ////////
            }
            , cols: [[
                { type: 'checkbox', fixed: 'left' }
                , {
                    field: 'id', width: 80, title: '', templet: function (d) {
                        if (d.ext == "" || d.ext == null)
                            return '<a href="pan?parentId=' + d.id + '"><i class="layui-icon" style="font-size: 42px; color: #1E9FFF;">&#xe622;</i></a> ';
                        if (d.ext.toUpperCase() == "GIF" || d.ext.toUpperCase() == "JPG" || d.ext.toUpperCase() == "JPEG" || d.ext.toUpperCase() == "BMP" || d.ext.toUpperCase() == "PNG")
                            return '<img class="aimg" nl=' + d.url + ' width=39 src=/images/icons/' + d.ext.toUpperCase() + '.png></img>'
                        return '<img width=39  src=/images/icons/' + d.ext.toUpperCase() + '.png></img>'
                    } }
                , { field: 'name', width: 300, title: '名称', style: "font-weight:bold", @if (Model.isCanUpdateFileName)
                                                            { @Html.Raw(" edit: 'text'"); } }

                , {
                    type: 'space', width: 50, title: '查看', templet: function (d) {
                        if (d.ext != "" && d.ext != null )
                            return '<a href="part/show?id=' + d.id + '" target="_blank" onclick="return c(this)"  class="layui-btn layui-btn-xs layui-btn-radius layui-btn-primary"> 查看 </a> ';
                        return "";
                    }}
                , {
                    type: 'space', width: 50, title: '下载', templet: function (d) {
                        if (d.ext != "" && d.ext != null )
                            return '<a href="part/show?id=' + d.id + '" target="_blank" onclick="return c(this)" class="layui-btn layui-btn-xs layui-btn-radius layui-btn-primary"> 下载 </a> ';
                        return "";
                    }
                }
                , { field: 'ext', width: 50, title: '格式' }

                , { field: 'useridx',  width: 80, title: '操作人' }
                , {
                    field: 'lasttime', width: 120, title: '上次修改时间', templet: function (d) {
                        return d.lasttime;
                    } }
                , { field: 'seqno', width: 50, title: '排序', @if (Model.isCanUpdateFileName)
                                                            { @Html.Raw(" edit: 'text'"); }
                }


                //, { field: 'status', width: 80, title: '状态', edit: 'text' }
                @if (Model.isAdmin)
                {
                    @Html.Raw(", { field: 'roles11', width: 250, title: '可上传' }");
                    @Html.Raw(", { field: 'roles22', width: 250, title: '可下载' }");
                    @Html.Raw(", { field: 'roles33', width: 250, title: '仅查看' }");
                    @Html.Raw(", { fixed: 'right', title: '权限', width: 100, align: 'center', toolbar: '#barDemo' }");
                }

            ]]
            , skin:'line'
        });
        //监听工具条
        table.on('tool(test5)', function (obj) {
            var data = obj.data;
            if (obj.event === 'detail') {
                layer.msg('ID：' + data.id + ' 的查看操作');
            } else if (obj.event === 'del') {
                layer.confirm('真的删除行么', function (index) {
                    obj.del();
                    layer.close(index);
                });
            } else if (obj.event === 'edit') {
                //layer.alert('编辑行：<br>' + JSON.stringify(data))

                var index=   parent.layer.open({
                    type: 2,
                    title:'请勾选',
                    area: ['700px', '450px'],
                    fixed: false, //不固定
                    maxmin: true,
                    cancel: function () {
                        reload();
                        //layer.msg('捕获就是从页面已经存在的元素上，包裹layer的结构', {time: 5000, icon:6});
                    },
                    content: 'part/pickall?panid=' + data.id
                });


               // parent.layer.full(index);
            }
        });
        //监听单元格编辑
        table.on('edit(test5)', function (obj) {
            var value = obj.value //得到修改后的值
                , data = obj.data //得到所在行所有键值
                , field = obj.field; //得到字段

            // layer.msg('[ID: ' + data.id + '] ' + field + ' 字段更改为：' + value);

            $.getJSON("/ajax/fieldupdate", { table: "pan", id: data.id, key: field, value: value }, function (json) {
                layer.msg(json.msg);
               // reload();
            });

        });

        var $ = layui.$, active = {
            getCheckData: function () {

                layer.confirm('您确定要删除吗？', {
                    btn: ['Yes', 'No'] //按钮
                }, function () {

                    //获取选中数据
                    var checkStatus = table.checkStatus('test5')
                        , data = checkStatus.data;
                    //layer.alert(JSON.stringify(data));
                    var ids = [];
                    for (var a in data) {
                        ids.push(data[a].id);
                    }
                    console.log(ids.join());
                    $.getJSON("/ajax/fieldupdate", { table: "pan", id: ids.join(), key: "status", value: -1 }, function (json) {
                        layer.msg(json.msg);
                        reload();
                    });


                }, function () {

                });

            }
            , getCheckLength: function () { //获取选中数目
                var checkStatus = table.checkStatus('test5')
                    , data = checkStatus.data;
                layer.msg('选中了：' + data.length + ' 个');
            }
            , isAll: function () { //验证是否全选
                var checkStatus = table.checkStatus('test5');
                layer.msg(checkStatus.isAll ? '全选' : '未全选');
            }
        };

        $('.demoTable2 .layui-btn').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });

    });
</script>
<script>
    $(function () { 

        $.getJSON("/ajax/pan/path", { parentid: parentId }, function (json) {
            $(window.parent.document).contents().find("#modulemenu > .nav").find(".path").remove();
            $(window.parent.document).contents().find("#mingnav").after(json.msg); 
        });
    })
    // window.parent.a();
  
</script>